### ISSUE TITLE
Error when removing field/s with ProcessWire's admin

### ISSUE THREAD

**Issue by jmartsch** [baumrock/RockMigrations#2]
When I am removing a field on a template in ProcessWire's admin, and RockMigrations is installed, I get an error:
`ProcessWire: ProcessTemplate: Invalid value for $existingItem argument`
![image](https://user-images.githubusercontent.com/551551/180771179-bfbb2e99-785a-4158-b5d4-f8b439081aa4.png)
The field is still present in the template afterwards.

I added this field by hand to the template just to try something out, then I wanted to remove it.

Normally if I try to remove a field a security question if I really want to delete this field appears, this doesn't happen with RockMigrations installed :( 

I know that there are methods for adding or removing fields with RockMigrations, but the native method of adding or removing fields in the admin should not interfere.

**Comment by BernhardBaumrock** [comment]
Hi Jens, can you please provide a reproducable step by step guide that demonstrates the issue on a fresh installation? I'll close the issue until then. Please reopen it once you have that informations. Thanks!
