### ISSUE TITLE
I don't think the modules directory can detect this way of presenting the version number for the module.

### ISSUE THREAD

**Issue by solonmedia** [baumrock/RockMigrations#21]
https://github.com/baumrock/RockMigrations/blob/1089f625048c4c68e883e46d1d57d7153c155bf2/RockMigrations.info.php#L7

For modules that use this method now to derive the module version from a local file, the module directory offers no answer for the latest module version:

![image](https://user-images.githubusercontent.com/58667283/227644288-6f17d203-3924-4c50-9c31-784259ef1b2e.png)

**Comment by BernhardBaumrock** [comment]
Hi @solonmedia thx for the report! I've already asked Ryan to add a feature to the modules directory to parse version numbers from package.json if one exists: https://github.com/processwire/processwire-issues/issues/1690
