### ISSUE TITLE
Usage of __DIR__ in $files->render() and symlinks

### ISSUE THREAD

**Issue by jlahijani** [baumrock/RockMigrations#22]
For various reasons, I have a directory that contains all the modules I use on my sites.  I then symlink that directory to be /site/modules/ to the site I'm working on.

With RM, you have this line in RockMigrations.module.php, which won't work with my symlinked setup because of how PW only includes files in allowed paths.
```
'value' => $this->wire->files->render(__DIR__ . "/profileeditor.php", [
```

Could you possibly change it to this instead?
```
'value' => $this->wire->files->render($this->path . "profileeditor.php", [
```

**Comment by BernhardBaumrock** [comment]
Sure, it's in the latest commit of the dev branch.

**Comment by jlahijani** [comment]
> Sure, it's in the latest commit of the dev branch.

Thanks, but you didn't remove this slash so technically you will have two slashes: /profileeditor.php
