### ISSUE TITLE
Assetss links

### ISSUE THREAD

**Issue by matjazpotocnik** [baumrock/RockMigrations#25]
![image](https://github.com/baumrock/RockMigrations/assets/7663992/359ac0ed-1aa9-4419-8b78-65869a9845bc)

Are you loading YT/google without a consent?

![image](https://github.com/baumrock/RockMigrations/assets/7663992/bdb4d184-d0d3-4bb2-8f1e-af4ddb10903e)

**Comment by BernhardBaumrock** [comment]
I've added youtube iframes to the module's config screen to provide helpful information / docs for the module. I guess that's what you are seeing?

**Comment by matjazpotocnik** [comment]
Yes, that's probably it; I'm not very happy having all sorts of cookies and tracking inside admin.

To comments the first screenshot: your assets are not loading as you have path to the them instead of urls.

**Comment by BernhardBaumrock** [comment]
Hey @matjazpotocnik thx, now I understand. Didn't see that you were talking about 2 different things.

I've just pushed a new version to the dev branch that removes the youtube iframes and that should also fix the file path issue - can you please confirm that as I'm not on windows any more?

**Comment by matjazpotocnik** [comment]
Tinycon - A small library for manipulating the Favicon, 2015. 

The root cause of all problems is the monaco editor. It's AMD loader that doesn't play nice with other javascripts. I remember I had troubles with them in my ProcessFileEditor and decided to get rid of it - I'm using CodeMirror, Adrian likes Ace.

**Comment by matjazpotocnik** [comment]
Bernhard, try this loader (rename it to loader.js) in profileeditor.js

[loader.txt](https://github.com/baumrock/RockMigrations/files/12176773/loader.txt)

**Comment by BernhardBaumrock** [comment]
Hi @matjazpotocnik thx for all your effort.

I've tried your loader and then I get these errors:

<img width="818" alt="image" src="https://github.com/baumrock/RockMigrations/assets/8488586/e7d59fef-9090-49b5-8fac-9fa84a6b78a4">

So not sure what to do about this. I'm using monaco because I can simply load it from CDN and it looks nice in my opinion and it works very similar to what I'm used to from VSCode. I have multicursor etc and the main keyboard shortcuts are the same as well.

Do you see any problems with that except the ugly error in the console? I've tried to load it via AJAX only, but then it breaks completely. So I think what we have now is the best we can get for minimal effort. It's just a console for superusers that might want to adjust some details when setting up a new site.

**Comment by matjazpotocnik** [comment]
i will get back to this next week...



Poslano iz naprave Galaxy



-------- Izvirno sporočilo --------
Od: Bernhard Baumrock ***@***.***>
Datum: 27. 7. 23 15:52 (GMT+01:00)
Za: baumrock/RockMigrations ***@***.***>
Kp: Matjaž Potočnik ***@***.***>, Mention ***@***.***>
Zadeva: Re: [baumrock/RockMigrations] Assetss links (Issue #25)


Hi @matjazpotocnik<https://github.com/matjazpotocnik> thx for all your effort.

I've tried your loader and then I get these errors:

[image]<https://user-images.githubusercontent.com/8488586/256555808-e7d59fef-9090-49b5-8fac-9fa84a6b78a4.png>

So not sure what to do about this. I'm using monaco because I can simply load it from CDN and it looks nice in my opinion and it works very similar to what I'm used to from VSCode. I have multicursor etc and the main keyboard shortcuts are the same as well.

Do you see any problems with that except the ugly error in the console? I've tried to load it via AJAX only, but then it breaks completely. So I think what we have now is the best we can get for minimal effort. It's just a console for superusers that might want to adjust some details when setting up a new site.

**Comment by matjazpotocnik** [comment]
Bernhard, try this:

```js
<link rel="stylesheet" data-name="vs/editor/editor.main" href="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.40.0/min/vs/editor/editor.main.min.css">
<script>
	var require = { paths: { vs: 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.40.0/min/vs' } };
</script>
<script src="/site/modules/RockMigrations/loader.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.40.0/min/vs/editor/editor.main.nls.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.40.0/min/vs/editor/editor.main.js"></script>

<script>
  var area = document.getElementById('editorvalue');
  var editor = monaco.editor.create(document.getElementById('editor'), {
      language: 'php',
      theme: 'vs-dark',
      value: area.value,
    });
  editor.getModel().onDidChangeContent((e) => {
    area.value = editor.getValue();
  });

  // auto-resize editor
  let ro = new ResizeObserver(() => {
    editor.layout()
  });
  ro.observe(document.querySelector("html"));
</script>
```

**Comment by BernhardBaumrock** [comment]
@matjazpotocnik unfortunately this does not work at all on my end.

Could you please provide the whole content of profileeditor.php so that I can just copy and paste?

**Comment by matjazpotocnik** [comment]
[profileeditor.zip](https://github.com/baumrock/RockMigrations/files/12209896/profileeditor.zip)

As you can see, the latest css change (https://github.com/processwire/processwire-issues/issues/1788) for label makes the icon jump to the new line....
![image](https://github.com/baumrock/RockMigrations/assets/7663992/85928662-94d5-4ae0-ba26-eb1c808ca8b2)

**Comment by BernhardBaumrock** [comment]
Thx @matjazpotocnik do you have a cdn link für the loader.js script?

**Comment by BernhardBaumrock** [comment]
<img width="1437" alt="image" src="https://github.com/baumrock/RockMigrations/assets/8488586/67222b80-842e-42d0-8e9d-df570c352196">

**Comment by BernhardBaumrock** [comment]
Hey @matjazpotocnik thx for the hint about the misaligned info icon. Do you know how to fix this? I tried "display:inline" but no change. I don't know why it moves to the next line, because it has more than enough space?!

**Comment by matjazpotocnik** [comment]
I don't have a cdn link for this loader, I even don't know how and where I got it. I had problems with ProcessFileManager in combo with monaco, and used this solution. It's an older version, but it works. 

Regarding the notes/error in the console:

- Permison-policy error: just ignore.
- JQMIGRATE: that's OK
- Source maps: I have disabled source maps in my dev tools, but you can also delete them from the loader.js, at the end of the file: `//# sourceMappingURL=../../min-maps/vs/loader.js.map`

I already provided the fix for the checkboxes.css:

> Maybe just removing white-space from .InputfieldCheckboxes ul li label would be enough?

**Comment by matjazpotocnik** [comment]
`tabs.click();` jQuery.fn.click() event shorthand is deprecated

**Comment by BernhardBaumrock** [comment]
thx @matjazpotocnik I'll fix this in the next version and make it a configurable tweak :)
