### ISSUE TITLE
migrateWatchFiles Out of Memory

### ISSUE THREAD

**Issue by nymr-carlb** [baumrock/RockMigrations#27]
Hello

Sorry I'm new to raising issues on GitHub so sorry if this isn't in the right format.

I've just upgraded my local dev site (PW 3.0.200) from 3.26.1 to 3.30.0 (also tried this on the intermediate releases)
Since 3.29.0 it now hangs on migrateWatchFiles() until PHP (8.1 Win x64) runs out of memory.

I use RockMigrations by setting up a directory to watch in ready.php

`// Setup Rock Migrations watches`
`$rm = $this->wire->modules->get('RockMigrations');`
`$rm->watch($wire->config->paths->site . 'migrations');`
`$rm->migrateWatchFiles(true);`

In that directory I have a PHP file for each feature area and edit each file as I'm developing. The idea being if I want to port the feature to another site I just copy the PHP file over to that site's migrations folder. It's been working pretty well up to now.

I've stripped out all my other site modules, templates and pages to see if this was a conflict and it's not helped.
I've not tried 3.30.0 in a fresh ProcessWire install because unfortunately I just don't have the time. 

Is this something I was doing wrong that is now fixed...or something I'm doing ok that's now bugged? (!)

Cheers

**Comment by BernhardBaumrock** [comment]
Hi @nymr-carlb thx for reaching out.

I've had a look and the update from 3.27 to 3.29 (not sure why it bumped the version by 2) was a bigger one. Though I'm not sure why it should cause an out of memory issue. 

You can have a look at this commit: https://github.com/baumrock/RockMigrations/commit/56004d8aab2ef844016029587d83187d01f4e7cb

I removed the feature that prevents migrations from running twice. Maybe that's causing an issue on your end?

I can't say if you are doing anything right or wrong unless you provide a reproducible code that I can use and test on a blank pw installation.

**Comment by nymr-carlb** [comment]
The documentation for watch files is a bit thin so I'm really not clear on how to use it - specifically _where_ to add the watch.

I've just tried this in a 'blank' site profile

```php
// /site/migrate.php (presumably?)

$rm = $this->wire->modules->get('RockMigrations');
$rm->watch($this->wire->config->paths->site . 'migrations', true, ['recursive' => true]); // Doesn't actually trigger migrations?
$rm->migrateWatchFiles(true); // Triggered migrations up to 3.29.0, now out of memory
``` 

```php
// /site/migrations/test.php

<?php

namespace ProcessWire;

/** @var RockMigrations $rm */
$rm = $this->wire->modules->get('RockMigrations');

// Add Test Fields
$rm->createFields([
    'test_field' => [
        'label' => 'Test Field',
        'type' => 'FieldtypeText',
        'collapsed' => 0,
        'tags' => 'test',
    ]
]);
```

**Comment by BernhardBaumrock** [comment]
Hi @nymr-carlb I haven't used the migrate.php file for awhile as I'm always using custom page classes and the magicpages feature! I'll have to have a closer look into your issue hopefully soon.

**Comment by BernhardBaumrock** [comment]
@nymr-carlb is this still an issue?
