### ISSUE TITLE
Argument in function createPage()

### ISSUE THREAD

**Issue by Clarity-Atlant** [baumrock/RockMigrations#33]
Hello, @BernhardBaumrock!

In function createPage() in RockMigrations.module.php:1076 there is an argument with strict typization: array $status. However, $status should be typized as int, since status should be integer.

Can you please fix it?

**Comment by BernhardBaumrock** [comment]
Thx for the report, the idea is to define the status as array. I've updated the docblock:

```
   * Usage:
   * $rm->createPage(
   *   template: 'foo',
   *   title: 'My foo page',
   *   parent: 1,
   *   status: ['hidden'],
   * );
```

Feel free to reopen the issue if you think that's still something to fix.

**Comment by BernhardBaumrock** [comment]
close
