### ISSUE TITLE
Tag support for PageFile and PageImage classes?

### ISSUE THREAD

**Issue by solonmedia** [baumrock/RockMigrations#35]
​
It looks like there is some extra work that needs to be complete for tag support on files and images.

If you try to create an images field that has the useTags field set using migrate() you will see what I mean. There is an expected column that doesn't get created by default.

There is some extra schema that needs to be worked out. I started doing some code for it but got sidetracked.

This is my pseudo - it doesn't work yet I don't think, but it's what I started before I got sidetracked. I insert this at [Rockmigrations.module.php:3593](https://github.com/baumrock/RockMigrations/blob/950476ff27256581c63467a6347929cae809cb2d/RockMigrations.module.php#L3593C1-L3593C1) :

    //If useTags flag is set, invoke the getDatabaseSchema method
    //to indirectly call the private updateDatabaseSchema function to create the tags column. JAG Added

    if (isset($data['useTags'])) {
      //bd($data['useTags']);
      $fieldtypeFile = $field->getFieldtype();
      $fieldtypeFile->getDatabaseSchema($field);
    }

You can find the updateDatabaseSchema functions in the wire/FieldtypeFile.module and wire/FieldtypeImage.module

​

**Comment by BernhardBaumrock** [comment]
@solonmedia is this still an issue?
