### ISSUE TITLE
Provide functional access to RockMigrations

### ISSUE THREAD

**Issue by hirasso** [baumrock/RockMigrations#41]
Hi there! Right now, RockMigrations needs to be referenced like this everywhere it's being used:

```php
/** @var RockMigrations $rm */
$rm = $this->wire->modules->get('RockMigrations');
$rm->...
```

How about providing a little helper function with the module, similar to [ProcessWire's functions API](https://processwire.com/api/ref/functions/)? That would make code completion feel much cleaner IMO. This little snippet in the module would be enough:

```js
/**
 * Provide access to RockMigrations
 * @return RockMigrations
 */
function rm(): RockMigrations {
	return wire()->modules->get('RockMigrations');
}
```

Than we could save us the additional like `$rm = $this->wire->modules->get('RockMigrations');` throughout our code bases by using the function directly:

```php
/** anywhere, migrate.php, page classes, ... */
rm()->migrate(...)
```
```

**Comment by BernhardBaumrock** [comment]
Nice idea, thx @hirasso check out the dev branch. Will be merged next month.

**Comment by hirasso** [comment]
@BernhardBaumrock woaaa that was fast! Looking forward! :)
