### ISSUE TITLE
Modifying existing repeaterMatrix fields

### ISSUE THREAD

**Issue by hirasso** [baumrock/RockMigrations#43]
Hi there! I just gave migrating repeater matrix fields another go. I'm testing with a field named `blocks`. This is the migration code from the panel:

```php
'blocks' => [
  'label' => 'Blocks',
  'flags' => 0,
  'type' => 'FieldtypeRepeaterMatrix',
  'template_id' => 0,
  'parent_id' => 0,
  'matrix1_name' => 'imageblock',
  'matrix1_label' => 'Image',
  'matrix1_head' => '{matrix_label} [• {matrix_summary}]',
  'matrix1_fields' => [
    0 => 'image',
    1 => 'aspect_ratio',
  ],
  'matrix1_sort' => 1,
  'matrix2_name' => 'textblock',
  'matrix2_label' => 'Text',
  'matrix2_head' => '{matrix_label} [• {matrix_summary}]',
  'matrix2_fields' => [
    0 => 'text',
    1 => 'text_size',
    2 => 'collapse',
  ],
  'matrix2_sort' => 2,
  'familyFriendly' => 0,
  'repeaterCollapse' => 3,
  'repeaterLoading' => 1,
  'rememberOpen' => 1,
  'accordionMode' => 0,
  'loudControls' => 1,
  'addType' => 1,
  'imageDefs' => 'imageblock:
textblock:
miroembed:
videoembed:',
  'imageStyle' => 'margin:10px; width:200px;',
  'imageText' => 1,
  'allowChangeType' => 2,
  'collapsed' => 0,
  'required' => 1,
  'matrix3_name' => 'miroembed',
  'matrix3_label' => 'Miro Embed',
  'matrix3_head' => '{matrix_label} [• {matrix_summary}]',
  'matrix3_fields' => [
    0 => 'miro_embed',
    1 => 'aspect_ratio',
  ],
  'matrix3_sort' => 3,
  'matrix4_name' => 'videoembed',
  'matrix4_label' => 'Video Embed',
  'matrix4_head' => '{matrix_label} [• {matrix_summary}]',
  'matrix4_fields' => [
    0 => 'image',
    1 => 'video_embed',
  ],
  'matrix4_sort' => 4,
  'tags' => '',
  'matrixN_sort' => '',
  'matrixN_name' => '',
  'matrixN_label' => '',
  'matrixN_fields' => '',
  'matrixN_head' => '{matrix_label} [• {matrix_summary}]',
  'matrixN_import' => '',
  'repeaterDepth' => '',
  'repeaterAddLabel' => '',
  'repeaterMaxItems' => '',
  'repeaterMinItems' => '',
  'lazyParents' => '',
  'allowMatrixTypes' => '',
  'showIf' => '',
  'themeOffset' => '',
  'themeBorder' => '',
  'themeColor' => '',
  'columnWidth' => 100,
  'requiredIf' => '',
]
```

I'm trying to re-create this programmatically, like this:

```php
$rm->setMatrixItems('blocks', [
	'imageblock' => [
		'label' => 'Image',
		'fields' => [
			'image',
			'aspect_ratio',
		]
	],
	'textblock' => [
		'label' => 'Text',
		'fields' => [
			'text',
			'text_size',
			'collapse'
		]
	],
	'videoembed' => [
		'label' => 'Video Embed',
		'fields' => [
			'image',
			'video_embed'
		]
	],
]);
/** Remove the miro-embed that was previously defined using the panel */
rm()->removeMatrixItem('blocks', 'miroembed');
```

The outcome: 

![CleanShot 2023-12-12 at 12 52 43@2x](https://github.com/baumrock/RockMigrations/assets/869813/a6400d86-09c4-41df-a27a-5ca229fd60d2)

All sub-fields are suddenly `Title` fields, and sometimes I even get an ominous field "Process", that seems to be something internal. The subfields (e.g. `image`, `aspect_ratio`, `text`, ...) are all defined in the database, but _not yet_ using RockMigrations. Maybe related?

**Comment by BernhardBaumrock** [comment]
@hirasso Thx for the report. I can't say anything about RepeaterMatrix fields as I'm not using it any more.

If you want a matrix field with first class support for migrations you can buy RockPageBuilder at baumrock.com

Maybe @gebeer can say anything to that issue as he is the one that provided the PR for RepeaterMatrix support?

**Comment by gebeer** [comment]
@hirasso looking at your migration, a potential issue here is with the structure of the fields array in the implementation. In the function definition for setMatrixItems(), each field in the fields array is itself an associative array with options like label and columnWidth. However, in the implementation, the fields are provided as indexed arrays with just the field names. This discrepancy could lead to unexpected behavior if the function expects the detailed configuration for each field. Note that the field configuration can be an empty array.

The adjusted code looks like this:
```php
$rm->setMatrixItems('blocks', [
    'imageblock' => [
        'label' => 'Image',
        'fields' => [
            'image' => [],
            'aspect_ratio' => [],
        ]
    ],
    'textblock' => [
        'label' => 'Text',
        'fields' => [
            'text' => [],
            'text_size' => [],
            'collapse' => [],
        ]
    ],
    'videoembed' => [
        'label' => 'Video Embed',
        'fields' => [
            'image' => [],
            'video_embed' => [],
        ]
    ],
]);
```
Please let me know if that works.
if not, I'll try and find some time tomorrow to investigate more, replicating your exact example on a blank PW install. In order for me to replicate this exact scenario, please provide the migrations for the fields used inside blocks.

**Comment by BernhardBaumrock** [comment]
@gebeer it would be nice if setMatrixItems took care about that automatically.  I'm doing it like this in setTemplateFields:

<img width="468" alt="image" src="https://github.com/baumrock/RockMigrations/assets/8488586/882157c6-11a0-4d17-b08e-f081bd0f3952">

**Comment by hirasso** [comment]
@gebeer I can confirm that it works if I provide empty arrays for all the fields in the matrix item fields! 🥳 ... @BernhardBaumrock 's suggestion for allowing naked field names as keys would be a very handy enhancement I think. Thanks so much for your support!

**Comment by gebeer** [comment]
@BernhardBaumrock @hirasso PR is out: https://github.com/baumrock/RockMigrations/pull/45
