### ISSUE TITLE
Provide migrations copy code for pages

### ISSUE THREAD

**Issue by jaresty** [baumrock/RockMigrations#44]
I really appreciate the copy code available from the template and field edit views for this module! It is really helpful for getting started on setting up a migration. Unfortunately, it does not appear that this workflow is set up yet for Pages[1].  Can you point me in the right direction? Is this work that still needs to be done?

[1]:https://github.com/baumrock/RockMigrations/blob/8f0a8b5031332ce21862c3d2db6dc56c7ae0ba23/RockMigrations.module.php#L4478-L4484

**Comment by BernhardBaumrock** [comment]
Pages are totally different when it comes to migrations. Pages often hold CONTENT and it's not easy to distinguish what is structure and what is user content. But creating pages is simple, see this example of RockCommerce.module.php:

```php
  public function migrate()
  {
    /** @var RockMigrations $rm */
    $rm = $this->wire->modules->get('RockMigrations');
    $rootPage = $rm->createPage(
      template: RootPage::tpl, // I'm using pageclass constants, but you can use strings as well
      parent: 1,
      name: "rc",
      title: "RockCommerce",
      status: ["hidden"],
    );
    $rm->createPage(
      template: Orders::tpl,
      parent: $rootPage,
      name: "orders",
      title: "Orders",
    );
    $rm->createPage(
      template: Webhooks::tpl,
      parent: $rootPage,
      name: "webhooks",
      title: "Webhooks",
      status: ["hidden"],
    );
    $invoicesPage = $rm->createPage(
      template: Invoices::tpl,
      parent: $rootPage,
      name: "invoices",
      title: "Invoices",
      status: ["hidden", "locked"],
    );
    $rm->createPage(
      template: InvoiceGroup::tpl,
      parent: $invoicesPage,
      name: "rockcommerce",
      title: "RockCommerce",
      status: ["hidden"],
    );
  }
```

This creates all the necessary pages for RockCommerce in the backend:

<img width="381" alt="image" src="https://github.com/baumrock/RockMigrations/assets/8488586/39506ed0-8046-4e84-898b-f3c5dfd3ebd0">

**Comment by jaresty** [comment]
Sorry, I didn't totally understand what you mean. Could you please provide a complete example of what is meant by:

>  Pages often hold CONTENT and it's not easy to distinguish what is structure and what is user content.
