### ISSUE TITLE
Updating pages via calling createPage or the migrate config array ignores existing title values in the DB if one is not supplied

### ISSUE THREAD

**Issue by solonmedia** [baumrock/RockMigrations#50]
If you wish to update a page rather than create it, the method will rename the title of the page to the name if you do not supply a title value in the array, overwriting the existing DB title value for the page.

I ran into this issue because I wanted to set unpublished permissions that already existed but were left unpublished to a status of published automatically.

This following code:

```
$rm->migrate([
    'pages' => [
        'page-action-move' => [
            'parent' => 'name=permissions,template=admin',
            'template' => 'permission',
            'status' => [
                'on',
            ],
        ],
    ],
]);
```

for example causes the page to update to published, but the page title becomes the page name. The original title value is lost.

The fix is relatively simple I think.

In the RockMigrations.module.php in the migrate() function around line 2830 in the //setup pages section, the createPage call should read:

```
   // setup pages
    foreach ($config->pages as $name => $data) {
      if (isset($data['name'])) {
        $name = $data['name'];
      } elseif (is_int($name)) {
        // no name provided
        $name = uniqid();
      }

      $d = $this->wire(new WireData());
      /** @var WireData $d */
      $d->setArray($data);
      $this->createPage(
        title: $d->title, //remove the ?: $name so this may be sent as null
        name: $name,
        template: $d->template,
        parent: $d->parent,
        status: $d->status,
        data: $d->data
      );
    }
```

In the RockMigrations.module.php in the createPage() function around line 1146 or so, the conditional operation should be:

```
   if ($page and $page->id) {
      $set_title = ($title) ? $title : $page->title; //check new title against existing title value
      $page->setAndSave('title', $set_title ?: $name); //if still no title, use $name
      $page->status($status ?: []);

      // if some page field values are provided we save them now
      if (is_array($data)) $page->setAndSave($data);

      return $page;
    }
```

**Comment by BernhardBaumrock** [comment]
Thx @solonmedia please check https://github.com/baumrock/RockMigrations/commit/07b06557d1af5e1f4c91e60e0fd48ca921ac80a6 :)
