### ISSUE TITLE
"RockMigrations Code" breaks on "<" character in description, notes

### ISSUE THREAD

**Issue by donatasben** [baumrock/RockMigrations#51]
Hi,
I've added some text in descriptions and notes, that is actual html tag and when RockMigrations markup for migration code is rendered in template edit page - it breaks on html "<" & ">" brackets (the rest of page is not being rendered after encountering such characters).
(Edit) Probably this happens only if it is within template context data. Tested inside default description field - it is rendered fine in migration code display.

I use a `DynamicDescriptionNotes` module that allows using HTML in notes and descriptions and I find it very useful. However it just turns off entity encoding to achieve this.

Would it be possible to take this into account on RockMigrations side?

For now I manually use "&lt;" and "&gt;" entities where I want to display these characters.

![SCR-20240206-qpqi](https://github.com/baumrock/RockMigrations/assets/4421344/e7f98872-600b-4693-91d5-e141117f7d70)
![SCR-20240206-qpsg](https://github.com/baumrock/RockMigrations/assets/4421344/04e57b4d-78d0-45ea-89fa-54807f29f1c9)

The culprit notes text:
![SCR-20240206-qqeu](https://github.com/baumrock/RockMigrations/assets/4421344/fbc5db30-f7ac-4c5a-9939-dadf23e405e0)

**Comment by BernhardBaumrock** [comment]
Hi @donatasben should be an easy fix. Could you please go to RockMigrations.module.php around line 4699 should be this code:

```php
    $form->add([
      'name' => '_RockMigrationsCopyInfo',
      'type' => 'markup',
      'label' => 'RockMigrations Code',
      'description' => 'This is the code you can use for your migrations. Use it in $rockmigrations->migrate():',
      'value' => "<pre><code>" . $this->getCode($item) . "</code></pre>",
      'collapsed' => Inputfield::collapsedYes,
      'icon' => 'code',
    ]);
```

... and change it to this:

```php

    $code = $this->wire->sanitizer->entities1($this->getCode($item));
    $form->add([
      'name' => '_RockMigrationsCopyInfo',
      'type' => 'markup',
      'label' => 'RockMigrations Code',
      'description' => 'This is the code you can use for your migrations. Use it in $rockmigrations->migrate():',
      'value' => "<pre><code>$code</code></pre>",
      'collapsed' => Inputfield::collapsedYes,
      'icon' => 'code',
    ]);
    $f = $form->get('_RockMigrationsCopyInfo');
    $form->remove($f);
    $form->insertBefore($f, $existing);
```

Does that fix the issue?

**Comment by BernhardBaumrock** [comment]
@donatasben pushed to the dev branch

would you mind sharing your admin theme with us?

**Comment by BernhardBaumrock** [comment]
Yeah it looks nice from what I see on the screenshot. I think it's a shame that we don't have more admin styles. I'm a little tired of AdminStyleRock and as I'm using darkmode it's a bit hard on the eyes nowadays. And it has very low contrast - yours looks better in that regard. Not sure if it's the screenshot or not though, so it would be nice to check it out.
