### ISSUE TITLE
Feature request: FieldtypeCombo support (ProFields module)

### ISSUE THREAD

**Issue by donatasben** [baumrock/RockMigrations#52]
It would be super awesome if you could implement support for adding, removing, sorting in FieldtypeCombo subfields (ProFields module from Ryan).
The actual code is already given by Ryan in the forum, data scheme can be viewed in the exported field JSON code, but it would be very convenient if we could use good-old RockMigrations for manipulating these fields too, just like you have for FieldtypeRepeaterMatrix.

The example code by Ryan for adding new subfield is here - https://processwire.com/talk/topic/29271-create-field-into-existing-combofield-trough-api/?do=findComment&comment=237481

Or if you don't have access:
```
// data for the new subfield you want to create 
// like what you see in the JSON, but without the 'i123_' prefixes
$data = [
  "type" => "Integer", // see types at top of ComboModuleConfig.php
  "label" => "Test integer",
  "name" => "test_integer",
  "columnWidth" => 100,
  "ok" => "1", // 1 means that it's ready to show in page editor
  "schemaType" => "n-int-small-u", // see schema types in ComboSchema.php
  "collapsed" => 0,
  "inputType" => "text", // "text" or "number"
  "size" => 10,
];

$field = $fields->get('test_combo'); // get the combo field
$i = $field->get('qty') + 1; // identify index for new field
foreach($data as $name => $value) { 
  // set data for new subfield using index we determined above
  $field->set("i{$i}_$name", $value); 
}
$field->set('qty', $i); // update the quantity of subfields
$field->order .= ",$i"; // append new subfield to CSV order string
$field->save(); // saving creates the subfield and updates the DB schema
```

**Comment by BernhardBaumrock** [comment]
Hey @donatasben I'm happy to add support for it, but I don't have any experience with the combo field and so I don't have any setup to test.

If you want me to do that I'm happy to implement it if you sponsor it, but it needs time to get everything setup and test everything etc.;

If you provide a PR I can merge it.
