### ISSUE TITLE
(request:MagicPages module) Make attachment of magic field methods optional 

### ISSUE THREAD

**Issue by netcarver** [baumrock/RockMigrations#59]
Whilst I understand this is useful to you, would you consider making [this feature of MagicPages](https://github.com/baumrock/RockMigrations/blob/be4138ed26d8aa0116ebdd21a79148d21574d546/MagicPages.module.php#L106) optional via a $config->rockMigrations setting?

Very happy for it to default to attaching the methods - but this is one aspect I'd like to be able to control on my installs. Wouldn't even need to be a configurable module setting, just something in site/config.php would do.

**Comment by BernhardBaumrock** [comment]
done, thx

**Comment by netcarver** [comment]
@BernhardBaumrock Perfect, thank you.

**Comment by MrSnoozles** [comment]
Thanks for the request and the implementation. I'm still using older versions of RockMigrations because right now it's doing too much for my setups. This helps 👍
Maybe all the magic utilities could even be split into a separate module for people that just want to use $rm->doSomething() from the CI?

**Comment by BernhardBaumrock** [comment]
This would mean a lot of work and refactoring on all my projects, as you can imagine. Do you want to sponsor this?
