### ISSUE TITLE
feat:docs Document attachment of magic field methods

### ISSUE THREAD

**Issue by netcarver** [baumrock/RockMigrations#60]
The module adds "magic field methods" via targetted hooks in the [addMagicFieldMethods()](https://github.com/baumrock/RockMigrations/blob/be4138ed26d8aa0116ebdd21a79148d21574d546/MagicPages.module.php#L106) method, but this is not mentioned in the [MagicPages](https://www.baumrock.com/en/processwire/modules/rockmigrations/docs/magicpages) documentation.

**Comment by BernhardBaumrock** [comment]
hi @netcarver I've added this, thank you.

**Comment by netcarver** [comment]
@BernhardBaumrock Thank you!
