### ISSUE TITLE
Wrong URL in logs

### ISSUE THREAD

**Issue by matjazpotocnik** [baumrock/RockMigrations#61]
![image](https://github.com/baumrock/RockMigrations/assets/7663992/dbe5e222-bc55-4675-974d-5efba30c0b43)

`<a href="<a  href=&quot;editor://open?file=C:/inetpub/wwwroot/site/modules/RockMigrations/RockMigrations.module.php&amp;line=2559&quot;>RockMigrations.module:2559</a>">&lt;a  href="editor://open?file=C:/inetpub/ww…</a>`

Looks odd to me. Shouldn't this be:

`<a href="editor://open?file=C:/inetpub/wwwroot/site/modules/RockMigrations/RockMigrations.module.php&line=2559>Open in editor</a>`

**Comment by BernhardBaumrock** [comment]
Hi @matjazpotocnik are you talking about these links in the logfile view?

<img width="991" alt="image" src="https://github.com/baumrock/RockMigrations/assets/8488586/3517b7c6-fd35-4594-846d-88a8adddecde">

The intention here is to get clickable links in the tracy log panel:

<img width="1305" alt="image" src="https://github.com/baumrock/RockMigrations/assets/8488586/644b7e58-ad2d-43c6-838d-a53dd0425317">

I was fine with having those ugly links in the core view as a price for that. If you have any better ideas please let me know and reopen the issue.

**Comment by matjazpotocnik** [comment]
Yes, I'm talking about these links. I don't mind what's the text, the issue I have is that it doesn't open the editor - I get HTTP Error 404.5 - Not Found.

**Comment by matjazpotocnik** [comment]
This is how it looks here:

![image](https://github.com/baumrock/RockMigrations/assets/7663992/19921231-2cc9-4636-bf50-fcaf6b28c24f)

**Comment by BernhardBaumrock** [comment]
Yes, it looks the same for me as you can see in the screenshot. I don't know of a way to add links with custom markup to that page. So I ignore that view and made it work just for the tracy panel.

**Comment by matjazpotocnik** [comment]
Aha, in tracy!

**Comment by BernhardBaumrock** [comment]
Yes, we'd need a PR for the core to support a feature like this in the core log view. But I didn't really see the need.
