### ISSUE TITLE
Add support for Magic Method `editFormContent` (and other similar methods) when editing repeater items directly

### ISSUE THREAD

**Issue by jlahijani** [baumrock/RockMigrations#63]
My webapp is developed in such a way that specific repeater items (which are technically pages as you surely know) are edited "directly", meaning not from the "for" page as repeaters are typically edited.  Let's call my repeater "order_line_items".

In my `/site/classes/OrderLineItemsRepeaterPage.php` I want to use the `editFormContent` method as I am doing for normal pages, however it seems RM does not support this use-case.  Is it possible to add?  Seems easy enough.

Edit: I suppose the more important question is does MagicPage even work on repeater pages?

**Comment by jlahijani** [comment]
I should note how I am currently doing it without RM.  In `/site/templates/admin.php`:

```php
$wire->addHookAfter('ProcessPageEdit::buildFormContent', function(HookEvent $event) {
  $page = $event->object->getPage();
  $form = $event->return;
  if($page->template=='repeater_order_line_items') {
    // code here...
  }
});
```

**Comment by BernhardBaumrock** [comment]
Hey @jlahijani please have a look at MagicPages.module.php pwInit(). If it does not work for repeater pages I guess wire->templates does not return them? Could you please check and play around with that? You can add a third param TRUE to the $rm->cache() call which will make it always return the result of the callback. Otherwise you have to do a modules refresh to clear the cache.

**Comment by jlahijani** [comment]
Actually it seems to work now / it's already supported.  Weird I didn't do anything differently yesterday and double checked I had everything in place.  Nice.

**Comment by BernhardBaumrock** [comment]
Maybe you just didn't do a modules refresh after adding the "use MagicPage" to your repeater pageclass?

**Comment by jlahijani** [comment]
Probably, but I can't be for sure.  But good to know that's something that needs to be done in the future.
