### ISSUE TITLE
Different behaviour installing FieldtypePageTitleLanguage and FieldtypeTextLanguage fields

### ISSUE THREAD

**Issue by ivangretsky** [baumrock/RockMigrations#69]
Good day @BernhardBaumrock !

Thanks for your work with this module. Will always write this line)

I am using Rock Migrations to initially setup a multilingual site. I am running this code to convert `title` field to its language version:

```
$rm->createField('title', [
    "label" => "Title",
    "type" => "FieldtypePageTitleLanguage",
]);
```

I have previously installed LanguageSupport module.

But I am getting a missing dependencies error: 
```
Fatal Error:    Uncaught ProcessWire\WireException: Module FieldtypePageTitleLanguage requires: LanguageSupportFields, FieldtypeTextLanguage Unable to install required module - FieldtypeTextLanguage.
``` 

This is not so much of a deal. But this error doesn't happen if I install FieldtypeTextLanguage field, as it auto-installs dependencies. And this one doesn't. Looks like an inconsistency.

**Comment by BernhardBaumrock** [comment]
Hi @ivangretsky do you have a suggested fix?

**Comment by ivangretsky** [comment]
Not really. But I think it should be handled just like InputfieldText and InputfieldTextarea. But when InputfieldTextLanguage is not installed, dependency of a dependency is missing. That might make it harder to deal with.

**Comment by BernhardBaumrock** [comment]
I'm not going to work on this any time soon. So if anybody wants to fix this with a PR please go ahead.

**Comment by ivangretsky** [comment]
Thanks for the response, @BernhardBaumrock !

For now I managed a work around this installing all the necessary modules first via Rock Migrations. It might even be the right and best way to do it anyway. And I am not fell capable to submit a PR for this soon either. So closing this.

But this little issue might signal that second level dependencies (dependencies of dependencies) cannot be resolved elsewhere. So let's keep it in mind.
