### ISSUE TITLE
module not installable via "Add module from directory"

### ISSUE THREAD

**Issue by jmartsch** [baumrock/RockMigrations#7]
In a fresh ProcessWire installation, I try to "Add module from directory" on the modules page.

![image](https://user-images.githubusercontent.com/551551/190923952-0de1d292-81db-4ef9-80e5-a07154779514.png)

When I press "Get module info" the page returns "The process returned no content."

**Comment by jmartsch** [comment]
Also the update of an old version does not work on the updates page

**Comment by BernhardBaumrock** [comment]
Thx for letting me know @jmartsch I've fixed that :)
