### ISSUE TITLE
Is there a $rm->setFieldLanguageValue() method

### ISSUE THREAD

**Issue by ivangretsky** [baumrock/RockMigrations#71]
Good day, @BernhardBaumrock !

Thanks for your migrations - I am now an active user)

There is $rm->setFieldLanguageValue() method [mentioned here](https://github.com/baumrock/RockMigrations/blob/61737fb1537fe63086907e7d602426858b87f117/RockMigrations.module.php#L983C1-L987C9). But it seems it is not defined. Was it lost somewhere? Was it planned but never implemented? What do you recommend instead?

Thanks!

**Comment by BernhardBaumrock** [comment]
Hey @ivangretsky  finally ;)
This method was part of RM1 and not yet transitioned to the "new" version of RM. I have added it, thx.
