### ISSUE TITLE
Is there a standard of what a RM method should return?

### ISSUE THREAD

**Issue by ivangretsky** [baumrock/RockMigrations#73]
Good day @BernhardBaumrock !

I was trying to fix an issue with a pr #72 . 

As I use RockMigrations from my own script, I need to examine a value that its method returns. It would be easier in my case if the return value would be consistent across methods. Like it should return an object to chain. Or a boolean to see if the migration was successful. I can see that some methods return something, others do not. 

Do you have any system for that yourself? How do you handle errors in migrations? Do you test the module?

I think I will be doing more work with RM so consider it important to understand your concepts and style to contribute wisely. 

P.S. If there are any recommendations or any other design concepts a contributor should know, please lead me to them.

**Comment by BernhardBaumrock** [comment]
Hey Ivan, could you please use the forum for such questions and only create issues in case there are issues?

RM is a quite complex module and I tried to be as consistent as possible with return values and with method parameters. This has led to RM1 -> RM2 transition, where I had to rewrite several methods. One example is that (almost?) all methods now have a "quiet" option as second parameter to make sure they don't produce any errors/output when run multiple times.

There is definitely room for improvement, but it's hard to do without introducing any breaking changes and that's something that has to be taken very seriously as RockMigrations is now everywhere in my own projects and quite a lot of people seem to be using it.

If you have good ideas let me know.

**Comment by ivangretsky** [comment]
Thanks for the answer!
