### ISSUE TITLE
do not force lowercase fieldnames in createField method

### ISSUE THREAD

**Issue by jmartsch** [baumrock/RockMigrations#8]
In my setup I have many camelCase fields and RockMigrations forces lowercase fieldnames in line 659.
Could this be deactivated? Or at least made as a setting if you want to force lowercase fieldnames?

**Comment by BernhardBaumrock** [comment]
thx @jmartsch I've removed that limitation :) b1fcdb673b1015858f78e41da7f7105da7115faa
